"use client";

import "./globals.css";
import { Providers } from "@/redux/provider";

import { PropsWithChildren } from "react";
import { Main } from "./components/layout/Main";

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <Providers>
        <Main> {children}</Main>
      </Providers>
    </html>
  );
}

// import "./globals.css";
// import { Providers } from "@/redux/provider";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <Providers>{children}</Providers>
//       </body>
//     </html>
//   );
// }
