"use client";

import "./globals.css";
import { darkTheme, lightTheme } from "./theme/themes";
import { Providers } from "@/redux/provider";

import {
  ThemeProvider,
  CssBaseline,
  Switch,
  FormControlLabel,
} from "@mui/material";
import { ChangeEvent, useState } from "react";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let [useDarkTheme, setUseDarkTheme] = useState(false);
  let [theme, setTheme] = useState(useDarkTheme ? darkTheme : lightTheme);

  const changeThemeHandler = (target: ChangeEvent, currentValue: boolean) => {
    setUseDarkTheme(currentValue);
    setTheme(currentValue ? darkTheme : lightTheme);
  };

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <Providers>
        <ThemeProvider theme={theme}>
          <body id="__next">
            <CssBaseline />
            <FormControlLabel
              control={
                <Switch
                  checked={useDarkTheme}
                  inputProps={{ "aria-label": "Dark Mode" }}
                  onChange={(target, value) =>
                    changeThemeHandler(target, value)
                  }
                ></Switch>
              }
              label="Dark Mode"
              labelPlacement="start"
            />
            {children}
          </body>
        </ThemeProvider>
      </Providers>
    </html>
  );
}

// import "./globals.css";
// import { Providers } from "@/redux/provider";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <Providers>{children}</Providers>
//       </body>
//     </html>
//   );
// }
